server:
  port: 8089
  
spring:
  application:
    name: credit-service
          
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka