eureka:
    client:
        fetchRegistry: false
        registerWithEureka: false
        serviceUrl:
            defaultZone: http://peer1:8761/eureka/
    instance:
        hostname: localhost
    server:
        enableSelfPreservation: false
server:
    port: 8761
